[package]
name = "idb-tap-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"

[build-dependencies]
tonic-build = "0.10"