name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frameworks:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install dependencies
      run: |
        brew install protobuf
        gem install xcpretty

    - name: Clean build directory
      run: |
        rm -rf build/
        rm -rf ~/Library/Developer/Xcode/DerivedData/FBSimulatorControl-*
        rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
        rm -rf ~/Library/Caches/com.apple.dt.Xcode
        
    - name: Build frameworks
      run: |
        # Clean first
        xcodebuild -project FBSimulatorControl.xcodeproj -alltargets clean
        
        # Build for ARM64 only
        export ARCHS=arm64
        export ONLY_ACTIVE_ARCH=NO
        export VALID_ARCHS=arm64
        
        # Build without xcpretty to see actual errors
        xcodebuild -project FBSimulatorControl.xcodeproj -scheme FBControlCore -sdk macosx -derivedDataPath build build || true
        
        # Now run the full build
        ./build.sh framework build
        
    - name: Verify frameworks built
      run: |
        echo "=== Checking built frameworks ==="
        ls -la build/Build/Products/Debug/
        test -d build/Build/Products/Debug/FBControlCore.framework
        test -d build/Build/Products/Debug/FBSimulatorControl.framework
        test -d build/Build/Products/Debug/FBDeviceControl.framework
        test -d build/Build/Products/Debug/XCTestBootstrap.framework
        echo "All frameworks built successfully"
        
    # Skip tests for now - they hang waiting for simulators
    # TODO: Fix simulator tests in CI environment
    # - name: Test frameworks
    #   timeout-minutes: 30
    #   run: |
    #     ./build.sh framework test
        
  build-companion:
    runs-on: macos-latest
    needs: build-frameworks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install dependencies
      run: |
        brew install protobuf

    - name: Clean build directory
      run: |
        rm -rf build/
        rm -rf ~/Library/Developer/Xcode/DerivedData/FBSimulatorControl-*
        rm -rf ~/Library/Developer/Xcode/DerivedData/idb_companion-*
        rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
        rm -rf ~/Library/Caches/com.apple.dt.Xcode
        
    - name: Build idb_companion
      run: |
        mkdir -p dist
        # Build for ARM64 only
        export ARCHS=arm64
        export ONLY_ACTIVE_ARCH=NO
        export VALID_ARCHS=arm64
        ./idb_build.sh idb_companion build ./dist
        
    - name: Verify build
      run: |
        # Check that binary exists
        test -f dist/bin/idb_companion
        
        # Check that frameworks exist
        test -d dist/Frameworks/FBControlCore.framework
        test -d dist/Frameworks/FBSimulatorControl.framework
        test -d dist/Frameworks/FBDeviceControl.framework
        test -d dist/Frameworks/XCTestBootstrap.framework
        
        # Check binary architecture
        file dist/bin/idb_companion
        lipo -info dist/bin/idb_companion
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: idb_companion-${{ github.sha }}
        path: dist/