name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.1.7-arkavo.1)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: true

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install dependencies
      run: |
        brew install protobuf
        
    - name: Create build directory
      run: mkdir -p dist

    - name: Build idb_companion with frameworks
      run: |
        ./idb_build.sh idb_companion build ./dist
        
    - name: Verify build output
      run: |
        echo "=== Build output structure ==="
        ls -la dist/
        ls -la dist/bin/
        ls -la dist/Frameworks/
        
    - name: Fix framework rpaths
      run: |
        # Fix rpaths to load frameworks from relative path
        cd dist/bin
        for framework in ../Frameworks/*.framework; do
          framework_name=$(basename "$framework" .framework)
          install_name_tool -change \
            "@rpath/${framework_name}.framework/Versions/A/${framework_name}" \
            "@loader_path/../Frameworks/${framework_name}.framework/Versions/A/${framework_name}" \
            idb_companion || true
        done
        
        # Add rpath for frameworks directory
        install_name_tool -add_rpath "@loader_path/../Frameworks" idb_companion || true
        
        # Verify dependencies
        echo "=== Dependencies check ==="
        otool -L idb_companion
        
    - name: Codesign frameworks and binary
      run: |
        # Sign frameworks first
        for framework in dist/Frameworks/*.framework; do
          codesign --force --deep --sign - "$framework"
        done
        
        # Sign the binary
        codesign --force --sign - dist/bin/idb_companion
        
    - name: Create release archive
      run: |
        cd dist
        VERSION="${{ github.event.inputs.version }}"
        ARCHIVE_NAME="idb_companion-${VERSION}-macos-$(uname -m).tar.gz"
        tar -czf "../${ARCHIVE_NAME}" bin Frameworks
        
        # Create checksum
        cd ..
        shasum -a 256 "${ARCHIVE_NAME}" > "${ARCHIVE_NAME}.sha256"
        
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: idb_companion ${{ github.event.inputs.version }}
        body: |
          ## idb_companion Release for arkavo-edge
          
          This release includes:
          - `idb_companion` binary
          - All required frameworks bundled
          - Self-contained deployment (no system installation required)
          
          ### Installation
          
          ```bash
          # Download and extract
          tar -xzf ${{ env.ARCHIVE_NAME }}
          
          # The binary is in bin/idb_companion
          # Frameworks are in Frameworks/
          ```
          
          ### Usage with arkavo-edge
          
          This build is optimized for use with [arkavo-edge](https://github.com/arkavo-org/arkavo-edge).
          
          ### Checksums
          
          See `${{ env.ARCHIVE_NAME }}.sha256` for verification.
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
        files: |
          ${{ env.ARCHIVE_NAME }}
          ${{ env.ARCHIVE_NAME }}.sha256